[2024-03-06T11:00:57.862-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-03-06T11:00:57.868-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-03-06T11:00:57.868-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-06T11:00:57.903-0300] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): TSLA> on 2024-01-16 00:00:00+00:00
[2024-03-06T11:00:57.907-0300] {standard_task_runner.py:60} INFO - Started process 19850 to run task
[2024-03-06T11:00:57.911-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'TSLA', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/get_stoks.py', '--cfg-path', '/tmp/tmpu97mex54']
[2024-03-06T11:00:57.912-0300] {standard_task_runner.py:88} INFO - Job 52: Subtask TSLA
[2024-03-06T11:00:57.946-0300] {task_command.py:423} INFO - Running <TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-16T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-06T11:00:57.997-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_stocks_dag' AIRFLOW_CTX_TASK_ID='TSLA' AIRFLOW_CTX_EXECUTION_DATE='2024-01-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-16T00:00:00+00:00'
[2024-03-06T11:00:58.519-0300] {history.py:222} ERROR - TSLA: No price data found, symbol may be delisted (1h 2024-01-15 -> 2024-01-16)
[2024-03-06T11:00:58.521-0300] {python.py:202} INFO - Done. Returned value was: None
[2024-03-06T11:00:58.528-0300] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=TSLA, execution_date=20240116T000000, start_date=20240306T140057, end_date=20240306T140058
[2024-03-06T11:00:58.568-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-06T11:00:58.579-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-06T12:04:28.258-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-03-06T12:04:28.291-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-03-06T12:04:28.294-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-06T12:04:28.348-0300] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): TSLA> on 2024-01-16 00:00:00+00:00
[2024-03-06T12:04:28.361-0300] {standard_task_runner.py:60} INFO - Started process 40041 to run task
[2024-03-06T12:04:28.393-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'TSLA', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/get_stoks.py', '--cfg-path', '/tmp/tmpan6mj2m9']
[2024-03-06T12:04:28.412-0300] {standard_task_runner.py:88} INFO - Job 38: Subtask TSLA
[2024-03-06T12:04:28.708-0300] {task_command.py:423} INFO - Running <TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-16T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-06T12:04:29.055-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_stocks_dag' AIRFLOW_CTX_TASK_ID='TSLA' AIRFLOW_CTX_EXECUTION_DATE='2024-01-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-16T00:00:00+00:00'
[2024-03-06T12:04:30.120-0300] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/dags/get_stoks.py", line 19, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-03-06T12:04:30.646-0300] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=TSLA, execution_date=20240116T000000, start_date=20240306T150428, end_date=20240306T150430
[2024-03-06T12:04:30.725-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 38 for task TSLA (index 0 is out of bounds for axis 0 with size 0; 40041)
[2024-03-06T12:04:30.773-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-06T12:04:30.867-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-06T12:15:51.474-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-03-06T12:15:51.521-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-03-06T12:15:51.522-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-06T12:15:51.667-0300] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): TSLA> on 2024-01-16 00:00:00+00:00
[2024-03-06T12:15:51.687-0300] {standard_task_runner.py:60} INFO - Started process 47630 to run task
[2024-03-06T12:15:51.704-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'TSLA', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/get_stoks.py', '--cfg-path', '/tmp/tmpaxyzfe8g']
[2024-03-06T12:15:51.707-0300] {standard_task_runner.py:88} INFO - Job 186: Subtask TSLA
[2024-03-06T12:15:52.029-0300] {task_command.py:423} INFO - Running <TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-16T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-06T12:15:52.331-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_stocks_dag' AIRFLOW_CTX_TASK_ID='TSLA' AIRFLOW_CTX_EXECUTION_DATE='2024-01-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-16T00:00:00+00:00'
[2024-03-06T12:15:52.928-0300] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/dags/get_stoks.py", line 19, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-03-06T12:15:52.989-0300] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=TSLA, execution_date=20240116T000000, start_date=20240306T151551, end_date=20240306T151552
[2024-03-06T12:15:53.042-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 186 for task TSLA (index 0 is out of bounds for axis 0 with size 0; 47630)
[2024-03-06T12:15:53.092-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-06T12:15:53.377-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-06T12:17:45.558-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-03-06T12:17:45.570-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-03-06T12:17:45.571-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-06T12:17:45.585-0300] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): TSLA> on 2024-01-16 00:00:00+00:00
[2024-03-06T12:17:45.590-0300] {standard_task_runner.py:60} INFO - Started process 49944 to run task
[2024-03-06T12:17:45.592-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'TSLA', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '244', '--raw', '--subdir', 'DAGS_FOLDER/get_stoks.py', '--cfg-path', '/tmp/tmp74fkrils']
[2024-03-06T12:17:45.594-0300] {standard_task_runner.py:88} INFO - Job 244: Subtask TSLA
[2024-03-06T12:17:45.663-0300] {task_command.py:423} INFO - Running <TaskInstance: get_stocks_dag.TSLA scheduled__2024-01-16T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-06T12:17:45.771-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_stocks_dag' AIRFLOW_CTX_TASK_ID='TSLA' AIRFLOW_CTX_EXECUTION_DATE='2024-01-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-16T00:00:00+00:00'
[2024-03-06T12:17:46.304-0300] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/dags/get_stoks.py", line 19, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-03-06T12:17:46.320-0300] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=TSLA, execution_date=20240116T000000, start_date=20240306T151745, end_date=20240306T151746
[2024-03-06T12:17:46.335-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 244 for task TSLA (index 0 is out of bounds for axis 0 with size 0; 49944)
[2024-03-06T12:17:46.369-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-06T12:17:46.392-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
