[2024-03-06T11:00:52.792-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_stocks_dag.MSFT scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-03-06T11:00:52.798-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_stocks_dag.MSFT scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-03-06T11:00:52.798-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-06T11:00:52.813-0300] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): MSFT> on 2024-01-16 00:00:00+00:00
[2024-03-06T11:00:52.817-0300] {standard_task_runner.py:60} INFO - Started process 19812 to run task
[2024-03-06T11:00:52.819-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'MSFT', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/get_stoks.py', '--cfg-path', '/tmp/tmpctmiduf6']
[2024-03-06T11:00:52.821-0300] {standard_task_runner.py:88} INFO - Job 50: Subtask MSFT
[2024-03-06T11:00:52.850-0300] {task_command.py:423} INFO - Running <TaskInstance: get_stocks_dag.MSFT scheduled__2024-01-16T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-06T11:00:52.900-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_stocks_dag' AIRFLOW_CTX_TASK_ID='MSFT' AIRFLOW_CTX_EXECUTION_DATE='2024-01-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-16T00:00:00+00:00'
[2024-03-06T11:00:53.465-0300] {history.py:222} ERROR - MSFT: No price data found, symbol may be delisted (1h 2024-01-15 -> 2024-01-16)
[2024-03-06T11:00:53.467-0300] {python.py:202} INFO - Done. Returned value was: None
[2024-03-06T11:00:53.472-0300] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=get_stocks_dag, task_id=MSFT, execution_date=20240116T000000, start_date=20240306T140052, end_date=20240306T140053
[2024-03-06T11:00:53.518-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-06T11:00:53.529-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-06T12:04:28.255-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_stocks_dag.MSFT scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-03-06T12:04:28.334-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_stocks_dag.MSFT scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-03-06T12:04:28.335-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-06T12:04:28.408-0300] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): MSFT> on 2024-01-16 00:00:00+00:00
[2024-03-06T12:04:28.434-0300] {standard_task_runner.py:60} INFO - Started process 40053 to run task
[2024-03-06T12:04:28.455-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'MSFT', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/get_stoks.py', '--cfg-path', '/tmp/tmppbpf57n2']
[2024-03-06T12:04:28.501-0300] {standard_task_runner.py:88} INFO - Job 35: Subtask MSFT
[2024-03-06T12:04:28.780-0300] {task_command.py:423} INFO - Running <TaskInstance: get_stocks_dag.MSFT scheduled__2024-01-16T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-06T12:04:29.105-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_stocks_dag' AIRFLOW_CTX_TASK_ID='MSFT' AIRFLOW_CTX_EXECUTION_DATE='2024-01-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-16T00:00:00+00:00'
[2024-03-06T12:04:30.358-0300] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/dags/get_stoks.py", line 19, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-03-06T12:04:30.650-0300] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=MSFT, execution_date=20240116T000000, start_date=20240306T150428, end_date=20240306T150430
[2024-03-06T12:04:30.801-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 35 for task MSFT (index 0 is out of bounds for axis 0 with size 0; 40053)
[2024-03-06T12:04:30.912-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-06T12:04:31.292-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-06T12:15:51.078-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_stocks_dag.MSFT scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-03-06T12:15:51.151-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_stocks_dag.MSFT scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-03-06T12:15:51.152-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-06T12:15:51.221-0300] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): MSFT> on 2024-01-16 00:00:00+00:00
[2024-03-06T12:15:51.232-0300] {standard_task_runner.py:60} INFO - Started process 47572 to run task
[2024-03-06T12:15:51.250-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'MSFT', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '181', '--raw', '--subdir', 'DAGS_FOLDER/get_stoks.py', '--cfg-path', '/tmp/tmp40kather']
[2024-03-06T12:15:51.255-0300] {standard_task_runner.py:88} INFO - Job 181: Subtask MSFT
[2024-03-06T12:15:51.490-0300] {task_command.py:423} INFO - Running <TaskInstance: get_stocks_dag.MSFT scheduled__2024-01-16T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-06T12:15:51.949-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_stocks_dag' AIRFLOW_CTX_TASK_ID='MSFT' AIRFLOW_CTX_EXECUTION_DATE='2024-01-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-16T00:00:00+00:00'
[2024-03-06T12:15:52.837-0300] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/dags/get_stoks.py", line 19, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-03-06T12:15:52.863-0300] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=MSFT, execution_date=20240116T000000, start_date=20240306T151551, end_date=20240306T151552
[2024-03-06T12:15:52.889-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 181 for task MSFT (index 0 is out of bounds for axis 0 with size 0; 47572)
[2024-03-06T12:15:52.931-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-06T12:15:52.995-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-06T12:17:43.795-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_stocks_dag.MSFT scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-03-06T12:17:43.808-0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_stocks_dag.MSFT scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-03-06T12:17:43.808-0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-06T12:17:43.824-0300] {taskinstance.py:2214} INFO - Executing <Task(_PythonDecoratedOperator): MSFT> on 2024-01-16 00:00:00+00:00
[2024-03-06T12:17:43.831-0300] {standard_task_runner.py:60} INFO - Started process 49877 to run task
[2024-03-06T12:17:43.835-0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'get_stocks_dag', 'MSFT', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '242', '--raw', '--subdir', 'DAGS_FOLDER/get_stoks.py', '--cfg-path', '/tmp/tmp9a_6yln8']
[2024-03-06T12:17:43.837-0300] {standard_task_runner.py:88} INFO - Job 242: Subtask MSFT
[2024-03-06T12:17:43.902-0300] {task_command.py:423} INFO - Running <TaskInstance: get_stocks_dag.MSFT scheduled__2024-01-16T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-06T12:17:44.011-0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='get_stocks_dag' AIRFLOW_CTX_TASK_ID='MSFT' AIRFLOW_CTX_EXECUTION_DATE='2024-01-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-16T00:00:00+00:00'
[2024-03-06T12:17:44.559-0300] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/dags/get_stoks.py", line 19, in get_history
    yfinance.Ticker(ticker).history(
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/base.py", line 77, in history
    return self._lazy_load_price_history().history(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/utils.py", line 103, in wrapper
    result = func(*args, **kwargs)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/yfinance/scrapers/history.py", line 226, in history
    logger.debug(f'{self.ticker}: yfinance received OHLC data: {quotes.index[0]} -> {quotes.index[-1]}')
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5389, in __getitem__
    return getitem(key)
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/datetimelike.py", line 379, in __getitem__
    result = cast("Union[Self, DTScalarOrNaT]", super().__getitem__(key))
  File "/home/luan/Documents/airflow-executores-local-celery/venv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 284, in __getitem__
    result = self._ndarray[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
[2024-03-06T12:17:44.580-0300] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=get_stocks_dag, task_id=MSFT, execution_date=20240116T000000, start_date=20240306T151743, end_date=20240306T151744
[2024-03-06T12:17:44.598-0300] {standard_task_runner.py:107} ERROR - Failed to execute job 242 for task MSFT (index 0 is out of bounds for axis 0 with size 0; 49877)
[2024-03-06T12:17:44.613-0300] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-06T12:17:44.649-0300] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
